# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 11:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u5b57')),
                ('token', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='token')),
                ('department', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='\u90e8\u95e8')),
                ('mobile', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='\u624b\u673a')),
                ('memo', models.TextField(blank=True, default=None, null=True, verbose_name='\u5907\u6ce8')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('valid_begin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type_id', models.CharField(choices=[(b'server', b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (b'Switch', b'\xe4\xba\xa4\xe6\x8d\xa2\xe6\x9c\xba'), (b'router', b'\xe8\xb7\xaf\xe7\x94\xb1\xe5\x99\xa8'), (b'safety', b'\xe5\xae\x89\xe5\x85\xa8\xe8\xae\xbe\xe5\xa4\x87'), (b'store', b'\xe5\x82\xa8\xe5\xad\x98')], default=b'server', max_length=64)),
                ('cabinets_column', models.CharField(blank=True, max_length=16, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c\xe6\x8e\x92\xe6\x95\xb0')),
                ('cabinet_num', models.CharField(blank=True, max_length=16, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c\xe5\x8f\xb7')),
                ('cabinet_order', models.CharField(blank=True, max_length=16, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c\xe4\xb8\xad\xe7\x9a\x84\xe5\xba\x8f\xe5\x8f\xb7')),
                ('guarantee_time', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe4\xbf\x9d\xe4\xbf\xae\xe6\x97\xb6\xe9\x97\xb4')),
                ('buy_date', models.DateField(blank=True, default=datetime.datetime(2017, 1, 1, 0, 0), null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '\u8d44\u4ea7\u8868',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1\xe7\xba\xbf')),
            ],
            options={
                'verbose_name_plural': '\u4e1a\u52a1\u7ebf\u8868',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('create_da', models.DateTimeField(auto_now_add=True)),
                ('asset_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset')),
            ],
            options={
                'verbose_name_plural': '\u9519\u8bef\u65e5\u5fd7\u8868',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name=b'\xe7\xbb\x84\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'verbose_name_plural': '\u4e3b\u673a\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='login_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '\u767b\u9646\u65e5\u5fd7\u8868',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe7\xae\xa1\xe7\x90\x86IP')),
                ('vlan_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'VlanIP')),
                ('intranet_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xe5\x86\x85\xe7\xbd\x91IP')),
                ('sn', models.CharField(max_length=64, unique=True, verbose_name=b'SN\xe5\x8f\xb7')),
                ('manufacture', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5236\u9020\u5546')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('port_num', models.SmallIntegerField(blank=True, null=True, verbose_name=b'\xe7\xab\xaf\xe5\x8f\xa3\xe4\xb8\xaa\xe6\x95\xb0')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset')),
            ],
            options={
                'verbose_name_plural': '\u7f51\u7edc\u8bbe\u5907',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name=b'\xe7\xbd\x91\xe5\x8d\xa1\xe5\x90\x8d\xe7\xa7\xb0')),
                ('hwaddr', models.CharField(max_length=64, verbose_name=b'\xe7\xbd\x91\xe5\x8d\xa1mac\xe5\x9c\xb0\xe5\x9d\x80')),
                ('netmask', models.CharField(max_length=64)),
                ('ipaddrs', models.CharField(max_length=256, verbose_name=b'ip\xe5\x9c\xb0\xe5\x9d\x80')),
                ('up', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '\u7f51\u5361\u8868',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=128, unique=True)),
                ('sn', models.CharField(max_length=64, unique=True, verbose_name=b'\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe5\x88\xb6\xe9\x80\xa0\xe5\x95\x86')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name=b'\xe7\xae\xa1\xe7\x90\x86IP')),
                ('work_ip', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1IP')),
                ('os_platform', models.CharField(blank=True, max_length=16, null=True, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f')),
                ('os_version', models.CharField(blank=True, max_length=16, null=True, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe7\x89\x88\xe6\x9c\xac')),
                ('cpu_count', models.IntegerField(blank=True, null=True, verbose_name=b'CPU\xe6\xa0\xb8\xe6\x95\xb0')),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'CPU\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('disk_capacity', models.FloatField(blank=True, null=True, verbose_name=b'\xe7\xa3\x81\xe7\x9b\x98\xe5\xae\xb9\xe9\x87\x8fGB')),
                ('mem_capacity', models.FloatField(blank=True, null=True, verbose_name=b'\xe5\x86\x85\xe5\xad\x98\xe5\xae\xb9\xe9\x87\x8fMB')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset')),
                ('hostgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.HostGroup')),
            ],
            options={
                'verbose_name_plural': '\u670d\u52a1\u5668\u8868',
            },
        ),
        migrations.CreateModel(
            name='TaskExecResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_hostname', models.CharField(max_length=32)),
                ('exec_command', models.CharField(blank=True, max_length=256, null=True)),
                ('exec_result', models.TextField()),
                ('result_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '\u4efb\u52a1\u6267\u884c\u7ed3\u679c\u8868',
            },
        ),
        migrations.CreateModel(
            name='TaskJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[(b'get_data', b'\xe6\x95\xb0\xe6\x8d\xae\xe9\x87\x87\xe9\x9b\x86'), (b'exec_cmd', b'cmd'), (b'exec_sls', b'\xe8\xbd\xaf\xe4\xbb\xb6\xe9\x83\xa8\xe7\xbd\xb2')], max_length=50)),
                ('exec_info', models.CharField(blank=True, max_length=128, null=True)),
                ('exec_date', models.DateTimeField(auto_now_add=True)),
                ('exec_user', models.ForeignKey(max_length=16, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '\u4efb\u52a1\u8bb0\u5f55\u8868',
            },
        ),
        migrations.AddField(
            model_name='taskexecresult',
            name='jobname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.TaskJob'),
        ),
        migrations.AddField(
            model_name='nic',
            name='server_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Server'),
        ),
        migrations.AddField(
            model_name='asset',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.BusinessUnit', verbose_name=b'\xe5\xb1\x9e\xe4\xba\x8e\xe7\x9a\x84\xe4\xb8\x9a\xe5\x8a\xa1\xe7\xba\xbf'),
        ),
    ]
