# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-08 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180608_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrensystem',
            name='name',
            field=models.CharField(max_length=64, verbose_name=b'\xe5\xad\x90\xe7\xb3\xbb\xe7\xbb\x9f'),
        ),
    ]
