# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-08 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20180608_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.BusinessUnit', verbose_name=b'\xe5\xb1\x9e\xe4\xba\x8e\xe7\x9a\x84\xe4\xb8\x9a\xe5\x8a\xa1\xe7\xba\xbf'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.BusinessUnit', verbose_name=b'\xe5\xb1\x9e\xe4\xba\x8e\xe7\x9a\x84\xe5\xad\x90\xe7\xb3\xbb\xe7\xbb\x9f'),
        ),
    ]
