# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-08 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20180608_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='business_unit',
        ),
        migrations.AlterUniqueTogether(
            name='cabinetsnum',
            unique_together=set([('name', 'cabinet_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='childrensystem',
            unique_together=set([('name', 'business_unit')]),
        ),
    ]
