# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-08 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20180608_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cabinet_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.CabinetsNum', verbose_name=b'\xe5\xb1\x9e\xe4\xba\x8e\xe5\x93\xaa\xe4\xb8\x80\xe4\xb8\xaa\xe6\x9c\xba\xe6\x9f\x9c'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cabinet_order',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c\xe4\xb8\xad\xe7\x9a\x84\xe5\xba\x8f\xe5\x8f\xb7'),
        ),
    ]
