# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20180608_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='guarantee_time',
            field=models.CharField(blank=True, default=b'3\xe5\xb9\xb4', max_length=64, null=True, verbose_name=b'\xe8\xb4\xa8\xe4\xbf\x9d\xe6\x9c\x9f'),
        ),
    ]
