# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-15 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20180615_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cabinet_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c\xe4\xb8\xad\xe7\x9a\x84\xe5\xba\x8f\xe5\x8f\xb7'),
        ),
    ]
