# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-20 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20180615_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskexecresult',
            name='exec_command',
        ),
        migrations.AddField(
            model_name='taskexecresult',
            name='exec_status',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(max_length=64, verbose_name=b'\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7'),
        ),
    ]
