# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-21 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20180620_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecresult',
            name='exec_status',
            field=models.CharField(choices=[(b'False', b'\xe5\xa4\xb1\xe8\xb4\xa5'), (b'True', b'\xe6\x88\x90\xe5\x8a\x9f')], default=b'False', max_length=32),
        ),
    ]
