# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-21 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_auto_20180621_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecresult',
            name='exec_command',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecresult',
            name='exec_status',
            field=models.CharField(choices=[(b'false', b'\xe5\xa4\xb1\xe8\xb4\xa5'), (b'success', b'\xe6\x88\x90\xe5\x8a\x9f'), (b'null', b'\xe6\x9c\xaa\xe7\x9f\xa5')], default=b'null', max_length=32),
        ),
    ]
