# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-28 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_auto_20180628_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_threebutton_permission',
            options={'verbose_name_plural': '\u6309\u94ae\u7684\u6743\u9650'},
        ),
    ]
