# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-28 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_auto_20180628_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_threebutton_permission',
            name='threebutton',
            field=models.ManyToManyField(blank=True, null=True, to='asset.user_group'),
        ),
    ]
