# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-29 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_auto_20180628_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_twomenu_permission',
            name='per_method',
            field=models.SmallIntegerField(choices=[(1, b'GET'), (2, b'POST')], default=1, verbose_name=b'\xe8\xaf\xb7\xe6\xb1\x82\xe6\x96\xb9\xe6\xb3\x95'),
        ),
    ]
