# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-03 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_group_twomenu_permission_per_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_threebutton_permission',
            name='threebutton',
            field=models.ManyToManyField(blank=True, null=True, to='asset.group_twomenu_permission'),
        ),
        migrations.AlterField(
            model_name='group_threebutton_permission',
            name='threebutton_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe6\x8c\x89\xe9\x92\xae\xe7\x9a\x84\xe5\x90\x8d\xe5\xad\x97'),
        ),
        migrations.AlterField(
            model_name='group_threebutton_permission',
            name='threebutton_url',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name=b'\xe6\x8c\x89\xe9\x92\xaeid'),
        ),
    ]
