# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-05 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_auto_20180703_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='hostgroup',
        ),
        migrations.AddField(
            model_name='server',
            name='hostgroup',
            field=models.ManyToManyField(blank=True, null=True, to='asset.HostGroup', verbose_name=b'\xe5\xb1\x9e\xe4\xba\x8e\xe7\x9a\x84\xe4\xb8\xbb\xe6\x9c\xba\xe7\xbb\x84'),
        ),
    ]
