# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0019_auto_20180705_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='hostgroup',
            field=models.ManyToManyField(to='asset.HostGroup', verbose_name=b'\xe5\xb1\x9e\xe4\xba\x8e\xe7\x9a\x84\xe4\xb8\xbb\xe6\x9c\xba\xe7\xbb\x84'),
        ),
    ]
